import {
  COORDINATE_CONVENTION,
  ENGINE_NAME,
  ENGINE_VERSION,
  REVIEW_NOTICE,
  REVIEW_STATUS,
  SCHEMA,
  formatZodIssues,
} from '../contracts/common.ts';
import { diag, type Diagnostic } from '../contracts/diagnostics.ts';
import { HOST_RESPONSIBILITIES, exportManifestSchema, type ExportManifest } from '../contracts/manifest.ts';
import type { ContactInterval } from '../contracts/plan.ts';
import type { RecipeDocument } from '../contracts/recipe.ts';
import type { BakedClip, ClipMetrics } from '../metrics/types.ts';
import { deriveContactSchedule } from '../plan/contactSchedule.ts';
import { getRigModel } from '../rig/model.ts';
import { TOLERANCES } from '../tolerances.ts';

/**
 * Export manifest construction and hashing (pure; `crypto.subtle` is available in browsers and
 * Node >= 20). The manifest travels next to the .glb and carries what the animation tracks cannot:
 * recipe identity and parameters, phases, contact schedule, cues, assumptions, unsupported
 * features, provenance and the fixed UNREVIEWED status. It creates no prescription and makes no
 * clinical claim.
 */

export const VALIDATION_STATEMENT =
  'Geometric checks only (contact residuals, planted-contact drift, surface penetration, bone lengths, joint limits, ' +
  'transition continuity and, when present, export round-trip fidelity). Passing them is NOT clinical validation: it says ' +
  'nothing about balance, tissue loading, muscle activity, safety or clinical correctness.';

export const ASSET_STATEMENT =
  'All proportions, geometry, meshes and motion are original synthetic content generated by this package. ' +
  'No motion capture, patient data or third-party assets are included.';

/** Round-trip evidence (from src/export) that can be folded into the manifest's validation block. */
export interface RoundTripSummary {
  framesCompared: number;
  maxPositionError: number;
  maxRotationError: number;
  maxBoneLengthRelError: number;
  maxRootError: number;
  withinTolerance: boolean;
  issues: readonly string[];
}

/**
 * The recipe semantics the manifest needs. `RecipeDefinition` satisfies it structurally; export
 * self-test fixtures provide their own clearly labelled values instead of borrowing a real id.
 */
export interface ManifestRecipeInfo {
  id: string;
  version: string;
  title: string;
  setup: readonly string[];
  assumptions: readonly string[];
  unsupported: readonly string[];
}

export interface BuildManifestInput {
  clip: BakedClip;
  /** Clip metrics from `analyzeClip`; `null` when they could not be computed (reported, never hidden). */
  metrics: ClipMetrics | null;
  /** Why metrics are null, if known. */
  metricsError?: string;
  recipe: ManifestRecipeInfo;
  recipeDoc: RecipeDocument;
  animationFileName: string;
  animationSha256: string;
  createdAt: string;
  /** Explicit contact schedule; defaults to `deriveContactSchedule(clip.plan)`. */
  contactSchedule?: readonly ContactInterval[];
  roundTrip?: RoundTripSummary;
}

const MAX_MANIFEST_DIAGNOSTICS = 100;

function sameParamValue(a: unknown, b: unknown): boolean {
  return a === b || (typeof a === 'number' && typeof b === 'number' && Number.isNaN(a) && Number.isNaN(b));
}

/** Per-sample diagnostics collapsed by (code, severity, subject): first occurrence + count. */
export function summarizeFrameDiagnostics(clip: BakedClip): Diagnostic[] {
  const groups = new Map<string, { first: Diagnostic; count: number }>();
  for (const frame of clip.frames) {
    for (const d of frame.diagnostics) {
      const key = `${d.code}|${d.severity}|${d.subject ?? ''}`;
      const g = groups.get(key);
      if (g) g.count++;
      else groups.set(key, { first: { ...d, time: d.time ?? frame.t }, count: 1 });
    }
  }
  const order = { error: 0, warning: 1, info: 2 } as const;
  const out = [...groups.values()]
    .sort((a, b) => order[a.first.severity] - order[b.first.severity] || b.count - a.count)
    .map(({ first, count }) =>
      count > 1 ? { ...first, message: `${first.message} (${count} samples; first at t=${(first.time ?? 0).toFixed(4)} s)` } : first,
    );
  return out.slice(0, MAX_MANIFEST_DIAGNOSTICS);
}

/** Numeric clip metrics plus the fixed tolerances they are judged against. */
export function metricsRecord(metrics: ClipMetrics | null, roundTrip?: RoundTripSummary): Record<string, number> {
  const rec: Record<string, number> = {};
  if (metrics) {
    for (const [k, v] of Object.entries(metrics)) {
      if (typeof v === 'number' && Number.isFinite(v)) rec[k] = v;
    }
    for (const [code, n] of Object.entries(metrics.diagnosticsByCode)) rec[`diagnostics.${code}`] = n;
  }
  if (roundTrip) {
    rec['roundTrip.framesCompared'] = roundTrip.framesCompared;
    rec['roundTrip.maxPositionError'] = roundTrip.maxPositionError;
    rec['roundTrip.maxRotationError'] = roundTrip.maxRotationError;
    rec['roundTrip.maxBoneLengthRelError'] = roundTrip.maxBoneLengthRelError;
    rec['roundTrip.maxRootError'] = roundTrip.maxRootError;
  }
  for (const [k, v] of Object.entries(TOLERANCES)) rec[`tolerance.${k}`] = v;
  return rec;
}

/**
 * Builds and validates the export manifest. Throws on programming errors (mismatched recipe
 * identity, parameters that differ from the ones the plan was compiled with, schema violations):
 * a manifest that misdescribes its animation must never be written.
 */
export function buildExportManifest(input: BuildManifestInput): ExportManifest {
  const { clip, metrics, recipe, recipeDoc } = input;
  const plan = clip.plan;
  if (recipeDoc.recipeId !== recipe.id || plan.recipe.id !== recipe.id) {
    throw new Error(
      `buildExportManifest: recipe identity mismatch (document '${recipeDoc.recipeId}', definition '${recipe.id}', plan '${plan.recipe.id}')`,
    );
  }
  for (const key of new Set([...Object.keys(plan.recipe.params), ...Object.keys(recipeDoc.params)])) {
    if (!sameParamValue(plan.recipe.params[key], recipeDoc.params[key])) {
      throw new Error(`buildExportManifest: parameter '${key}' differs between the recipe document and the compiled plan`);
    }
  }
  if (clip.frames.length === 0 || clip.frames.length !== clip.times.length) {
    throw new Error('buildExportManifest: clip has no frames or times/frames length mismatch');
  }

  const schedule = input.contactSchedule ?? deriveContactSchedule(plan);
  const model = getRigModel(clip.rig);

  const diagnostics: Diagnostic[] = [];
  if (!metrics) {
    diagnostics.push(
      diag('UNSUPPORTED_CONFIGURATION', 'error', `Geometric clip metrics were not computed${input.metricsError ? `: ${input.metricsError}` : ''}.`, {
        hint: 'The export is not geometrically validated; do not rely on contact or limit fidelity.',
      }),
    );
  } else {
    for (const f of metrics.failures) diagnostics.push(diag('UNSUPPORTED_CONFIGURATION', 'error', `Geometric tolerance failed: ${f}`));
  }
  if (input.roundTrip && !input.roundTrip.withinTolerance) {
    diagnostics.push(
      diag('EXPORT_MISMATCH', 'error', 'Export -> reimport comparison exceeded tolerance.', {
        value: input.roundTrip.maxPositionError,
        limit: TOLERANCES.exportPosition,
      }),
    );
    for (const issue of input.roundTrip.issues) diagnostics.push(diag('EXPORT_MISMATCH', 'error', issue));
  }
  diagnostics.push(...summarizeFrameDiagnostics(clip));

  const assumptions = [...new Set([...recipe.assumptions, ...plan.assumptions])];
  const last = clip.times[clip.times.length - 1]!;

  const manifest: ExportManifest = {
    schema: SCHEMA.manifest,
    reviewStatus: REVIEW_STATUS,
    reviewNotice: REVIEW_NOTICE,
    hostResponsibilities: [...HOST_RESPONSIBILITIES],
    recipe: {
      schema: recipeDoc.schema,
      recipeId: recipeDoc.recipeId,
      reviewStatus: recipeDoc.reviewStatus,
      params: Object.fromEntries(Object.keys(recipeDoc.params).sort().map((k) => [k, recipeDoc.params[k]!] as const)),
      provenance: { ...recipeDoc.provenance },
    },
    recipeTitle: recipe.title,
    recipeVersion: recipe.version,
    setup: [...recipe.setup],
    phases: plan.phases.map((p) => ({ id: p.id, label: p.label, start: p.start, end: p.end })),
    contactSchedule: schedule.map((c) => ({ id: c.id, site: c.site, surface: c.surface, kind: c.kind, start: c.start, end: c.end })),
    cues: plan.cues.map((c) => ({ id: c.id, t: c.t, phaseId: c.phaseId, label: c.label })),
    assumptions,
    unsupported: [...recipe.unsupported],
    rig: { id: clip.rig.id, name: clip.rig.name, fingerprint: model.fingerprint },
    convention: { ...COORDINATE_CONVENTION },
    bake: {
      fps: clip.fps,
      frameCount: clip.frames.length,
      duration: Math.max(plan.duration, last),
      solverTier: clip.tier,
      interpolation: 'LINEAR',
    },
    provenance: {
      generator: ENGINE_NAME,
      generatorVersion: ENGINE_VERSION,
      createdAt: input.createdAt,
      synthetic: true,
      assets: ASSET_STATEMENT,
    },
    validation: {
      kind: 'geometric-only',
      statement: VALIDATION_STATEMENT,
      metrics: metricsRecord(metrics, input.roundTrip),
      withinTolerance: metrics !== null && metrics.withinTolerance && (input.roundTrip?.withinTolerance ?? true),
      diagnostics,
    },
    files: { animation: input.animationFileName, animationSha256: input.animationSha256 },
  };

  const parsed = exportManifestSchema.safeParse(manifest);
  if (!parsed.success) {
    throw new Error(`buildExportManifest: manifest violates ${SCHEMA.manifest}: ${formatZodIssues(parsed.error).join('; ')}`);
  }
  return parsed.data;
}

/** Pretty JSON with a trailing newline. */
export function manifestToJson(manifest: ExportManifest): string {
  return `${JSON.stringify(manifest, null, 2)}\n`;
}

/** Lower-case hex SHA-256 of the given bytes, via Web Crypto (browser and Node). */
export async function sha256Hex(bytes: ArrayBuffer | ArrayBufferView): Promise<string> {
  const subtle = (globalThis as { crypto?: Crypto }).crypto?.subtle;
  if (!subtle) throw new Error('sha256Hex: crypto.subtle is unavailable (requires a secure context in browsers)');
  // isView rather than instanceof ArrayBuffer: buffers can come from another realm (workers, test VMs).
  const view = ArrayBuffer.isView(bytes)
    ? new Uint8Array(bytes.buffer, bytes.byteOffset, bytes.byteLength)
    : new Uint8Array(bytes);
  const digest = await subtle.digest('SHA-256', view as Uint8Array<ArrayBuffer>);
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, '0')).join('');
}
