import {
  COORDINATE_CONVENTION,
  ENGINE_NAME,
  ENGINE_VERSION,
  REVIEW_NOTICE,
  REVIEW_STATUS,
  SCHEMA,
  formatZodIssues,
} from '../contracts/common.ts';
import { diag, type Diagnostic, type DiagnosticCode } from '../contracts/diagnostics.ts';
import { HOST_RESPONSIBILITIES, exportManifestSchema, type ExportManifest } from '../contracts/manifest.ts';
import type { ContactInterval } from '../contracts/plan.ts';
import type { RecipeDocument } from '../contracts/recipe.ts';
import type { BakedClip, ClipMetrics } from '../metrics/types.ts';
import { deriveContactSchedule } from '../plan/contactSchedule.ts';
import { getRigModel } from '../rig/model.ts';
import { TOLERANCES } from '../tolerances.ts';

/**
 * Export manifest construction and hashing (pure; `crypto.subtle` is available in browsers and
 * Node >= 20). The manifest travels next to the .glb and carries what the animation tracks cannot:
 * recipe identity and parameters, phases, contact schedule, cues, assumptions, unsupported
 * features, provenance and the fixed UNREVIEWED status. It creates no prescription and makes no
 * clinical claim.
 */

export const VALIDATION_STATEMENT =
  'Geometric checks only (contact residuals, planted-contact drift, surface penetration, bone lengths, joint limits, ' +
  'transition continuity and, when present, export round-trip fidelity). Passing them is NOT clinical validation: it says ' +
  'nothing about balance, tissue loading, muscle activity, safety or clinical correctness.';

export const ASSET_STATEMENT =
  'All proportions, geometry, meshes and motion are original synthetic content generated by this package. ' +
  'No motion capture, patient data or third-party assets are included.';

/** Round-trip evidence (from src/export) that can be folded into the manifest's validation block. */
export interface RoundTripSummary {
  framesCompared: number;
  maxPositionError: number;
  maxRotationError: number;
  maxBoneLengthRelError: number;
  maxRootError: number;
  withinTolerance: boolean;
  issues: readonly string[];
}

/**
 * The recipe semantics the manifest needs. `RecipeDefinition` satisfies it structurally; export
 * self-test fixtures provide their own clearly labelled values instead of borrowing a real id.
 */
export interface ManifestRecipeInfo {
  id: string;
  version: string;
  title: string;
  setup: readonly string[];
  assumptions: readonly string[];
  unsupported: readonly string[];
}

export interface BuildManifestInput {
  clip: BakedClip;
  /** Clip metrics from `analyzeClip`; `null` when they could not be computed (reported, never hidden). */
  metrics: ClipMetrics | null;
  /** Why metrics are null, if known. */
  metricsError?: string;
  recipe: ManifestRecipeInfo;
  recipeDoc: RecipeDocument;
  animationFileName: string;
  animationSha256: string;
  createdAt: string;
  /** Explicit contact schedule; defaults to `deriveContactSchedule(clip.plan)`. */
  contactSchedule?: readonly ContactInterval[];
  roundTrip?: RoundTripSummary;
}

const MAX_MANIFEST_DIAGNOSTICS = 100;

function sameParamValue(a: unknown, b: unknown): boolean {
  return a === b || (typeof a === 'number' && typeof b === 'number' && Number.isNaN(a) && Number.isNaN(b));
}

/** Maps an `analyzeClip` failure line to the closest diagnostic code (generic fallback otherwise). */
export function failureCode(failure: string): DiagnosticCode {
  const f = failure.toLowerCase();
  if (f.startsWith('contact position') || f.startsWith('planted displacement')) return 'CONTACT_POSITION_VIOLATION';
  if (f.startsWith('contact orientation')) return 'CONTACT_ORIENTATION_VIOLATION';
  if (f.startsWith('penetration')) return 'SURFACE_PENETRATION';
  if (f.includes('outside joint limits')) return 'JOINT_LIMIT_CLAMPED';
  if (f.includes('non-converged')) return 'SOLVER_NOT_CONVERGED';
  if (f.includes('unreachable')) return 'TARGET_UNREACHABLE';
  if (f.includes('knee flip')) return 'KNEE_PLANE_DEGENERATE';
  return 'TOLERANCE_EXCEEDED';
}

/** Per-sample diagnostics collapsed by (code, severity, subject): first occurrence + count. */
export function summarizeFrameDiagnostics(clip: BakedClip): Diagnostic[] {
  const groups = new Map<string, { first: Diagnostic; count: number }>();
  for (const frame of clip.frames) {
    for (const d of frame.diagnostics) {
      const key = `${d.code}|${d.severity}|${d.subject ?? ''}`;
      const g = groups.get(key);
      if (g) g.count++;
      else groups.set(key, { first: { ...d, time: d.time ?? frame.t }, count: 1 });
    }
  }
  const order = { error: 0, warning: 1, info: 2 } as const;
  const out = [...groups.values()]
    .sort((a, b) => order[a.first.severity] - order[b.first.severity] || b.count - a.count)
    .map(({ first, count }) =>
      count > 1 ? { ...first, message: `${first.message} (${count} samples; first at t=${(first.time ?? 0).toFixed(4)} s)` } : first,
    );
  return out.slice(0, MAX_MANIFEST_DIAGNOSTICS);
}

/** Numeric clip metrics plus the fixed tolerances they are judged against. */
export function metricsRecord(metrics: ClipMetrics | null, roundTrip?: RoundTripSummary): Record<string, number> {
  const rec: Record<string, number> = {};
  if (metrics) {
    for (const [k, v] of Object.entries(metrics)) {
      if (typeof v === 'number' && Number.isFinite(v)) rec[k] = v;
    }
    for (const [code, n] of Object.entries(metrics.diagnosticsByCode)) rec[`diagnostics.${code}`] = n;
  }
  if (roundTrip) {
    rec['roundTrip.framesCompared'] = roundTrip.framesCompared;
    rec['roundTrip.maxPositionError'] = roundTrip.maxPositionError;
    rec['roundTrip.maxRotationError'] = roundTrip.maxRotationError;
    rec['roundTrip.maxBoneLengthRelError'] = roundTrip.maxBoneLengthRelError;
    rec['roundTrip.maxRootError'] = roundTrip.maxRootError;
  }
  for (const [k, v] of Object.entries(TOLERANCES)) rec[`tolerance.${k}`] = v;
  return rec;
}

/**
 * Builds and validates the export manifest. Throws on programming errors (mismatched recipe
 * identity, parameters that differ from the ones the plan was compiled with, schema violations):
 * a manifest that misdescribes its animation must never be written.
 */
export function buildExportManifest(input: BuildManifestInput): ExportManifest {
  const { clip, metrics, recipe, recipeDoc } = input;
  const plan = clip.plan;
  if (recipeDoc.recipeId !== recipe.id || plan.recipe.id !== recipe.id) {
    throw new Error(
      `buildExportManifest: recipe identity mismatch (document '${recipeDoc.recipeId}', definition '${recipe.id}', plan '${plan.recipe.id}')`,
    );
  }
  for (const key of new Set([...Object.keys(plan.recipe.params), ...Object.keys(recipeDoc.params)])) {
    if (!sameParamValue(plan.recipe.params[key], recipeDoc.params[key])) {
      throw new Error(`buildExportManifest: parameter '${key}' differs between the recipe document and the compiled plan`);
    }
  }
  if (clip.frames.length === 0 || clip.frames.length !== clip.times.length) {
    throw new Error('buildExportManifest: clip has no frames or times/frames length mismatch');
  }

  const schedule = input.contactSchedule ?? deriveContactSchedule(plan);
  const model = getRigModel(clip.rig);

  const diagnostics: Diagnostic[] = [];
  if (!metrics) {
    diagnostics.push(
      diag('UNSUPPORTED_CONFIGURATION', 'error', `Geometric clip metrics were not computed${input.metricsError ? `: ${input.metricsError}` : ''}.`, {
        hint: 'The export is not geometrically validated; do not rely on contact or limit fidelity.',
      }),
    );
  } else {
    for (const f of metrics.failures) diagnostics.push(diag(failureCode(f), 'error', `Geometric tolerance failed: ${f}`));
  }
  if (input.roundTrip && !input.roundTrip.withinTolerance) {
    diagnostics.push(
      diag('EXPORT_MISMATCH', 'error', 'Export -> reimport comparison exceeded tolerance.', {
        value: input.roundTrip.maxPositionError,
        limit: TOLERANCES.exportPosition,
      }),
    );
    for (const issue of input.roundTrip.issues) diagnostics.push(diag('EXPORT_MISMATCH', 'error', issue));
  }
  diagnostics.push(...summarizeFrameDiagnostics(clip));

  const assumptions = [...new Set([...recipe.assumptions, ...plan.assumptions])];
  const last = clip.times[clip.times.length - 1]!;

  const manifest: ExportManifest = {
    schema: SCHEMA.manifest,
    reviewStatus: REVIEW_STATUS,
    reviewNotice: REVIEW_NOTICE,
    hostResponsibilities: [...HOST_RESPONSIBILITIES],
    recipe: {
      schema: recipeDoc.schema,
      recipeId: recipeDoc.recipeId,
      reviewStatus: recipeDoc.reviewStatus,
      params: Object.fromEntries(Object.keys(recipeDoc.params).sort().map((k) => [k, recipeDoc.params[k]!] as const)),
      provenance: { ...recipeDoc.provenance },
    },
    recipeTitle: recipe.title,
    recipeVersion: recipe.version,
    setup: [...recipe.setup],
    phases: plan.phases.map((p) => ({ id: p.id, label: p.label, start: p.start, end: p.end })),
    contactSchedule: schedule.map((c) => ({ id: c.id, site: c.site, surface: c.surface, kind: c.kind, start: c.start, end: c.end })),
    cues: plan.cues.map((c) => ({ id: c.id, t: c.t, phaseId: c.phaseId, label: c.label })),
    assumptions,
    unsupported: [...recipe.unsupported],
    rig: { id: clip.rig.id, name: clip.rig.name, fingerprint: model.fingerprint },
    convention: { ...COORDINATE_CONVENTION },
    bake: {
      fps: clip.fps,
      frameCount: clip.frames.length,
      duration: Math.max(plan.duration, last),
      solverTier: clip.tier,
      interpolation: 'LINEAR',
    },
    provenance: {
      generator: ENGINE_NAME,
      generatorVersion: ENGINE_VERSION,
      createdAt: input.createdAt,
      synthetic: true,
      assets: ASSET_STATEMENT,
    },
    validation: {
      kind: 'geometric-only',
      statement: VALIDATION_STATEMENT,
      metrics: metricsRecord(metrics, input.roundTrip),
      withinTolerance: metrics !== null && metrics.withinTolerance && (input.roundTrip?.withinTolerance ?? true),
      diagnostics,
    },
    files: { animation: input.animationFileName, animationSha256: input.animationSha256 },
  };

  const parsed = exportManifestSchema.safeParse(manifest);
  if (!parsed.success) {
    throw new Error(`buildExportManifest: manifest violates ${SCHEMA.manifest}: ${formatZodIssues(parsed.error).join('; ')}`);
  }
  return parsed.data;
}

/** Pretty JSON with a trailing newline. */
export function manifestToJson(manifest: ExportManifest): string {
  return `${JSON.stringify(manifest, null, 2)}\n`;
}

const toHex = (bytes: Uint8Array): string => [...bytes].map((b) => b.toString(16).padStart(2, '0')).join('');

const SHA256_K = new Uint32Array([
  0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5, 0xd807aa98, 0x12835b01,
  0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174, 0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc,
  0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da, 0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147,
  0x06ca6351, 0x14292967, 0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
  0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070, 0x19a4c116, 0x1e376c08,
  0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3, 0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208,
  0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
]);

/**
 * Pure SHA-256 (FIPS 180-4). Used only when Web Crypto is unavailable (e.g. a page served over
 * plain http from a LAN address is not a secure context and has no `crypto.subtle`).
 */
export function sha256HexPure(input: Uint8Array): string {
  const bitLen = input.length * 8;
  const padded = new Uint8Array(((input.length + 9 + 63) >> 6) << 6);
  padded.set(input);
  padded[input.length] = 0x80;
  const dv = new DataView(padded.buffer);
  dv.setUint32(padded.length - 8, Math.floor(bitLen / 0x100000000), false);
  dv.setUint32(padded.length - 4, bitLen >>> 0, false);
  const h = new Uint32Array([0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19]);
  const w = new Uint32Array(64);
  const rotr = (x: number, n: number) => (x >>> n) | (x << (32 - n));
  for (let off = 0; off < padded.length; off += 64) {
    for (let i = 0; i < 16; i++) w[i] = dv.getUint32(off + i * 4, false);
    for (let i = 16; i < 64; i++) {
      const a = w[i - 15]!;
      const b = w[i - 2]!;
      const s0 = rotr(a, 7) ^ rotr(a, 18) ^ (a >>> 3);
      const s1 = rotr(b, 17) ^ rotr(b, 19) ^ (b >>> 10);
      w[i] = (w[i - 16]! + s0 + w[i - 7]! + s1) >>> 0;
    }
    let a = h[0]!, b = h[1]!, c = h[2]!, d = h[3]!, e = h[4]!, f = h[5]!, g = h[6]!, k = h[7]!;
    for (let i = 0; i < 64; i++) {
      const t1 = (k + (rotr(e, 6) ^ rotr(e, 11) ^ rotr(e, 25)) + ((e & f) ^ (~e & g)) + SHA256_K[i]! + w[i]!) >>> 0;
      const t2 = ((rotr(a, 2) ^ rotr(a, 13) ^ rotr(a, 22)) + ((a & b) ^ (a & c) ^ (b & c))) >>> 0;
      k = g;
      g = f;
      f = e;
      e = (d + t1) >>> 0;
      d = c;
      c = b;
      b = a;
      a = (t1 + t2) >>> 0;
    }
    h[0] = (h[0]! + a) >>> 0;
    h[1] = (h[1]! + b) >>> 0;
    h[2] = (h[2]! + c) >>> 0;
    h[3] = (h[3]! + d) >>> 0;
    h[4] = (h[4]! + e) >>> 0;
    h[5] = (h[5]! + f) >>> 0;
    h[6] = (h[6]! + g) >>> 0;
    h[7] = (h[7]! + k) >>> 0;
  }
  const out = new Uint8Array(32);
  const ov = new DataView(out.buffer);
  h.forEach((x, i) => ov.setUint32(i * 4, x, false));
  return toHex(out);
}

/**
 * Lower-case hex SHA-256 of the given bytes via Web Crypto (browser and Node); falls back to
 * `sha256HexPure` when `crypto.subtle` is unavailable (non-secure browser contexts).
 */
export async function sha256Hex(bytes: ArrayBuffer | ArrayBufferView): Promise<string> {
  // isView rather than instanceof ArrayBuffer: buffers can come from another realm (workers, test VMs).
  const view = ArrayBuffer.isView(bytes)
    ? new Uint8Array(bytes.buffer, bytes.byteOffset, bytes.byteLength)
    : new Uint8Array(bytes);
  const subtle = (globalThis as { crypto?: Crypto }).crypto?.subtle;
  if (!subtle) return sha256HexPure(view);
  const digest = await subtle.digest('SHA-256', view as Uint8Array<ArrayBuffer>);
  return toHex(new Uint8Array(digest));
}
