/**
 * Generates docs/RECIPES.md from the recipe registry, so the recipe documentation cannot drift
 * from the code. Usage: node scripts/recipes-doc.ts
 */
import { writeFileSync } from 'node:fs';
import { REVIEW_NOTICE } from '../src/core/contracts/common.ts';
import { listRecipes } from '../src/core/recipes/registry.ts';
import { compileRecipe } from '../src/core/recipes/registry.ts';
import { deriveContactSchedule } from '../src/core/plan/contactSchedule.ts';
import { createRigA } from '../src/core/rig/canonical.ts';

const rig = createRigA();
const out: string[] = [
  '# Recipes (generated)',
  '',
  `> ${REVIEW_NOTICE}`,
  '',
  'Generated by `node scripts/recipes-doc.ts` from `src/core/recipes/*`. Recipes are selected by explicit id only.',
  '',
];
for (const r of listRecipes()) {
  out.push(`## \`${r.id}\` — ${r.title}`, '', r.summary, '', `Version ${r.version}. Required rig capabilities: ${r.requiredCapabilities.map((c) => `\`${c}\``).join(', ')}.`, '');
  out.push('### Setup', '', ...r.setup.map((s) => `- ${s}`), '');
  out.push('### Phases', '', ...r.phaseOutline.map((p) => `- **${p.label}** (\`${p.id}\`): ${p.description}`), '');
  out.push('### Contact changes', '', ...r.contactChanges.map((s) => `- ${s}`), '');
  out.push('### Supported parameters', '', '| Key | Label | Range / options | Default | Meaning |', '|---|---|---|---|---|');
  for (const p of r.paramSpecs) {
    if (p.kind === 'number') out.push(`| \`${p.key}\` | ${p.label} | ${p.min}–${p.max} ${p.unit} (step ${p.step}) | ${p.default} | ${p.description} |`);
    else out.push(`| \`${p.key}\` | ${p.label} | ${p.options.join(' / ')} | ${p.default} | ${p.description} |`);
  }
  out.push('', '### Unsupported configurations', '', ...r.unsupported.map((s) => `- ${s}`), '');
  const c = compileRecipe(r.id, r.defaults(), rig);
  if (c.ok) {
    out.push(`### Compiled defaults on ${rig.name}`, '', `Duration ${c.plan.duration.toFixed(2)} s, feasible: ${c.feasible}.`, '');
    out.push('| Phase | Start (s) | End (s) | Description |', '|---|---|---|---|');
    for (const p of c.plan.phases) out.push(`| ${p.label} | ${p.start.toFixed(2)} | ${p.end.toFixed(2)} | ${p.description} |`);
    out.push('', '| Contact | Kind | Surface | Start (s) | End (s) | Blend in/out (s) |', '|---|---|---|---|---|---|');
    for (const k of deriveContactSchedule(c.plan)) out.push(`| \`${k.site}\` | ${k.kind}${k.segment ? ` (${k.segment})` : ''} | ${k.surface} | ${k.start.toFixed(2)} | ${k.end.toFixed(2)} | ${k.blendIn}/${k.blendOut} |`);
    out.push('', '### Authoring assumptions (compiled plan)', '', ...[...r.assumptions, ...c.plan.assumptions].map((s) => `- ${s}`), '');
  } else out.push(`Compile of defaults FAILED: ${c.diagnostics.map((d) => d.message).join('; ')}`, '');
}
writeFileSync('docs/RECIPES.md', `${out.join('\n')}\n`);
console.log('wrote docs/RECIPES.md');
